### ISSUE TITLE
regression with grid sims

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/descwl-shear-sims#99]
This sim is now giving 0.15% bias
```yaml
# same as v1 but now we are saving the mask frac
epochs_per_band: 1

gals_type: "exp"

gals_kws:
    mag: 22

layout_type: "grid"
layout_kws:
    dim: 8

wcs_kws:
    dither_range: [-0.5, 0.5]
    position_angle_range: [0, 360]
    scale_frac_std: 0.01
    shear_std: 0.01

psf_type: "ps"
psf_kws:
    variation_factor: 1.0
```
